version: '3'

services:
  mysql:
    image: mysql:8.1
    container_name: mysql-container
    ports:
      - "3310:3306"
      - "33010:33060"
    environment:
      MYSQL_ROOT_PASSWORD: gB5v79wnRS
      MYSQL_DATABASE: mental_health
      MYSQL_USER: manager
      MYSQL_PASSWORD: RGaqrgXG8W
    volumes:
      - ./init.sql:/data/application/init.sql

  golang-app:
    build:
      context: .
    image: mental-health-server
    restart: always
    container_name: mental-health-server
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: mental_health
      DATABASE_USER: root
      DATABASE_PASSWORD: gB5v79wnRS
      TELEGRAM_API_TOKEN: 6453650751:AAFoZ34iJSHl3J4t8zj6OYidL9dMfDgYoKE