version: '3'

services:
  mysql:
    image: mysql:8.1
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: gB5v79wnRS
      MYSQL_DATABASE: mental_health
      MYSQL_USER: manager
      MYSQL_PASSWORD: RGaqrgXG8W
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql

  backend:
    build:
      context: ./backend/
    image: mental-health-backend
    restart: always
    container_name: mental-health-backend
    ports:
      - "8123:8080"
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: mental_health
      DATABASE_USER: root
      DATABASE_PASSWORD: gB5v79wnRS
      TELEGRAM_API_TOKEN: 6453650751:AAFoZ34iJSHl3J4t8zj6OYidL9dMfDgYoKE

  client:
    build:
      context: ./client/
    image: mental-health-client
    restart: always
    container_name: mental-health-client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      REACT_APP_HOST: localhost
      REACT_APP_Port: 8123
